### ISSUE TITLE
Make this a set of ansible Roles ?

### ISSUE THREAD

**Issue by DanieleVistalli** [ebasso/ansible-ibm-websphere#1]
Hello Enio, I noticed your project and I think it's really useful.

Are you actively working / maintaining it ?
I'v currently forked it and I was wondering if you think it would make sense to transform your work into a set of Ansible roles.

We're going to test out your code soon and we'll provide feedback. Are you interested to it ?

**Comment by ebasso** [comment]
Hi Daniele

Thx for contact. Yes, i'm working on it, but not have time to transform on roles. 

I very interested to do this.

**Comment by DanieleVistalli** [comment]
It's good to know the project is alive.

We're working on roles to sanitize the Linux environment for IBM ICS/DX products... and your work is of real interest to me so.. maybe we'll fork and do some work on it.

take a look (just started) https://github.com/Factor-y/ansible-ibm-ics-roles

**Comment by ebasso** [comment]
Hi @DanieleVistalli now as roles. Enjoy!

**Comment by DanieleVistalli** [comment]
You're great, I'll go for a test round with it soon. Thanks for letting me know.
