### ISSUE TITLE
ihs_plg_wct.rsp.j2 , problem !

### ISSUE THREAD

**Issue by svx59** [ebasso/ansible-ibm-websphere#2]
Hello!
I ask to help with an ensemble role: "ibm-http-server-install\vars\"
In the file "main.yml" there is a line "__tpl_file:             "ihs_plg_wct.rsp.j2""
What is this file "**ihs_plg_wct.rsp.j2**"? that should be in the Inside?

I get an error:
/roles/ibm-http-server-install : Generate Response file] ************************************************************************************************
fatal: [host1]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to find 'ihs_plg_wct.rsp.j2' in expected paths."}

thank you in advance

**Comment by ebasso** [comment]
my .gitignore has blocked to upload templates directory. Thanks @svx59

**Comment by svx59** [comment]
**Thanks for help**
